Update README.md
nymea/nymea-plugins-zigbee pull request #40
Opened 2022-11-12 20:52 UTC by wayneoutthere

Attempted to update 2 URLS to dead links in Motion sensor and dimmer switch

2022-11-12 20:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nymea/nymea-plugins-zigbee?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nymea/nymea-plugins-zigbee?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nymea/nymea-plugins-zigbee?pullRequest=40) it.</sub>

2022-11-12 22:34 UTC, mzanetti requested changes
There's one issue with the dimmer switch link. the others look fine. Thanks!

2022-11-12 22:34 UTC, mzanetti commented on zigbeephilipshue/README.md
> +The [Hue dimmer switch](https://www.philips-hue.com/en-us/p/hue-dimmer-switch--latest-model-/046677562779  https://www.philips-hue.com/en-us/p/hue-dimmer-switch--latest-model-/046677562779) (includin
I think a MD link tag can't have 2 links. Besides, isn't it the same link twice? Looks like a copy/paste mistake maybe?

2022-11-12 22:53 UTC, wayneoutthere commented on zigbeephilipshue/README.md
> +The [Hue dimmer switch](https://www.philips-hue.com/en-us/p/hue-dimmer-switch--latest-model-/046677562779  https://www.philips-hue.com/en-us/p/hue-dimmer-switch--latest-model-/046677562779) (includin
hows' that?

2022-11-12 22:56 UTC, mzanetti approved these changes

2022-11-13 21:28 UTC, mzanetti approved these changes

2022-11-13 23:32 UTC, wayneoutthere commented
nice! you've built up my self worth, self esteem and will-to-live! ;)

2022-12-21 13:11 UTC, merged